Rename groupId, maven artifactId to org.jvnet.jaxb / jaxb-maven-plugin
highsource/maven-jaxb2-plugin pull request #263
Opened 2023-05-12 06:23 UTC by laurentschoelens

Fix for [GH-262](https://github.com/highsource/maven-jaxb2-plugin/issues/262)
Renaming to new groupId / artifactId / packages to ignore any future changes of maven / jaxb versions (preparing the v3 jakarta migration).

As pointed in the other PR, I think starting from 2.X version, this repo should be renamed to jaxb-tools and get merged with jaxb_basics and jaxb_annotate (and any other "plugins" that are commonly used by users of this jaxb-maven-plugin).
Also jaxb_basics has some PR waiting (dependencies updates for security fixes) that could be merged in before merged in this new mainstream repo.

2023-05-12 22:31 UTC, mattrpav commented
@laurentschoelens go ahead and rebase this one now, i just released 0.15.3

2023-05-13 06:41 UTC, laurentschoelens commented
Not an expert on rebase but I guess my new commit will do the job 😄

2023-05-13 06:42 UTC, laurentschoelens commented
Just found that not all projects has been updated to 0.15.4-SNAPSHOT after the release

2023-05-13 11:03 UTC, laurentschoelens commented
@mattrpav : done https://github.com/highsource/jaxb2-basics/pull/167 to jaxb2-basics to fix one issue. Guess we should do the renaming part too there (like org.jvnet.jaxb.commons package, org.jvnet.jaxb.commons groupid ?) by removing jaxb2 ref ?

2023-05-13 19:18 UTC, mattrpav commented
@laurentschoelens ready for the version bump and rename change for 2.x

Be sure you have a remote tracking branch linked to your fork
```
$ git remove -v
```

Should show something like this:
```
origin	https://github.com/mattrpav/maven-jaxb2-plugin.git (fetch)
origin	https://github.com/mattrpav/maven-jaxb2-plugin.git (push)
upstream	https://github.com/highsource/maven-jaxb2-plugin.git (fetch)
upstream	https://github.com/highsource/maven-jaxb2-plugin.git (push)
```

With 'origin' as your forked repo. Do this git flow to rebase
```
#1 $ git checkout $branchName
#2 $ git rebase -i upstream/main
#3 (in git editor - aka vi) .. set 'p' for pick first commit
#4 .. set 's' for squash for rest of commits
#5 .. work through changes / conflicts
#6 $ git rebase --continue
#7 $ git push origin $branchName -f
```

Moving forward, let's name branches for the issue like this:

Example branch for issue #267
```
$ git checkout -b mjp-267
```

2023-05-13 20:44 UTC, laurentschoelens commented
> @laurentschoelens ready for the version bump and rename change for 2.x
> 
> Be sure you have a remote tracking branch linked to your fork
> 
> ```
> $ git remove -v
> ```
> 
> Should show something like this:
> 
> ```
> origin	https://github.com/mattrpav/maven-jaxb2-plugin.git (fetch)
> origin	https://github.com/mattrpav/maven-jaxb2-plugin.git (push)
> upstream	https://github.com/highsource/maven-jaxb2-plugin.git (fetch)
> upstream	https://github.com/highsource/maven-jaxb2-plugin.git (push)
> ```
> 
> With 'origin' as your forked repo. Do this git flow to rebase
> 
> ```
> #1 $ git checkout $branchName
> #2 $ git rebase -i upstream/main
> #3 (in git editor - aka vi) .. set 'p' for pick first commit
> #4 .. set 's' for squash for rest of commits
> #5 .. work through changes / conflicts
> #6 $ git rebase --continue
> #7 $ git push origin $branchName -f
> ```
> 
> Moving forward, let's name branches for the issue like this:
> 
> Example branch for issue #267
> 
> ```
> $ git checkout -b mjp-267
> ```

Without the interactive rebase, that's what I did
Redoing it soon with your last commit
Ok for future branch naming

2023-05-14 07:20 UTC, laurentschoelens commented
> @laurentschoelens ready for the version bump and rename change for 2.x
> 
> Be sure you have a remote tracking branch linked to your fork
> 
> ```
> $ git remove -v
> ```
> 
> Should show something like this:
> 
> ```
> origin	https://github.com/mattrpav/maven-jaxb2-plugin.git (fetch)
> origin	https://github.com/mattrpav/maven-jaxb2-plugin.git (push)
> upstream	https://github.com/highsource/maven-jaxb2-plugin.git (fetch)
> upstream	https://github.com/highsource/maven-jaxb2-plugin.git (push)
> ```
> 
> With 'origin' as your forked repo. Do this git flow to rebase
> 
> ```
> #1 $ git checkout $branchName
> #2 $ git rebase -i upstream/main
> #3 (in git editor - aka vi) .. set 'p' for pick first commit
> #4 .. set 's' for squash for rest of commits
> #5 .. work through changes / conflicts
> #6 $ git rebase --continue
> #7 $ git push origin $branchName -f
> ```
> 
> Moving forward, let's name branches for the issue like this:
> 
> Example branch for issue #267
> 
> ```
> $ git checkout -b mjp-267
> ```

Rebase done and forced push to my repository. PR updated according to latest changes.
Tested OK on JDK8 / JDK11
Next step ? Updating jaxb-basics and jaxb-annotate before merging here ?
If so, should we name jaxb-basics and jaxb-annotate with groupId like `org.jvnet.jaxb.basics` / `org.jvnet.jaxb.annotate` to avoid artifactId collision with plugin artifacts ?

2023-05-15 20:43 UTC, laurentschoelens commented on plugin-core/src/main/java/org/jvnet/jaxb/AbstractXJC2Mojo.java
> +package org.jvnet.jaxb;
OK for base package name
Shouldn't we do the same for groupid ? To avoid collision with other jaxb tools

2023-05-16 00:10 UTC, mattrpav commented on plugin-core/src/main/java/org/jvnet/jaxb/AbstractXJC2Mojo.java
> +package org.jvnet.jaxb;
Hah, shared groupId should work well here. Really large projects use more of a 'flat' approach w/ Maven GroupId coordinates.

2023-05-16 06:55 UTC, laurentschoelens commented on plugin-core/src/main/java/org/jvnet/jaxb/AbstractXJC2Mojo.java
> +package org.jvnet.jaxb;
Commit amended, this should be fixed.
Also changed the package from main plugin project from `mjiip` (stands for **M**aven-**J**axb**2**(ii in roman)-**P**lugin) to `jaxb.maven`

2023-06-10 16:29 UTC, mattrpav requested changes

2023-06-10 16:29 UTC, mattrpav commented on plugin-core/src/main/java/org/jvnet/jaxb/maven/IOptionsFactory.java
> +public interface IOptionsFactory<O> {
Why rename to IOptionsFactory?

2023-06-10 18:27 UTC, mattrpav approved these changes
LGTM

2023-06-10 18:27 UTC, merged